-- Users synced from Authentik via OIDC token
CREATE TABLE IF NOT EXISTS users (
    id           BIGSERIAL PRIMARY KEY,
    sub          VARCHAR(255) UNIQUE NOT NULL,
    username     VARCHAR(100) NOT NULL,
    email        VARCHAR(255),
    created_at   TIMESTAMP DEFAULT NOW()
);

-- Daily question sets generated by Claude
CREATE TABLE IF NOT EXISTS question_sets (
    id           BIGSERIAL PRIMARY KEY,
    set_date     DATE UNIQUE NOT NULL,
    theme        VARCHAR(150) NOT NULL,
    generated_at TIMESTAMP DEFAULT NOW()
);

-- Individual questions belonging to a set
CREATE TABLE IF NOT EXISTS questions (
    id              BIGSERIAL PRIMARY KEY,
    question_set_id BIGINT REFERENCES question_sets(id),
    position        INT NOT NULL,
    question_text   TEXT NOT NULL,
    option_a        TEXT NOT NULL,
    option_b        TEXT NOT NULL,
    option_c        TEXT NOT NULL,
    option_d        TEXT NOT NULL
);

-- One submission per user per question set (all 5 answers at once)
CREATE TABLE IF NOT EXISTS answers (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT REFERENCES users(id),
    question_set_id BIGINT REFERENCES question_sets(id),
    answer_1        CHAR(1) NOT NULL,
    answer_2        CHAR(1) NOT NULL,
    answer_3        CHAR(1) NOT NULL,
    answer_4        CHAR(1) NOT NULL,
    answer_5        CHAR(1) NOT NULL,
    submitted_at    TIMESTAMP DEFAULT NOW(),
    UNIQUE(user_id, question_set_id)
);
