ALTER TABLE answers
    ADD COLUMN notes_1 VARCHAR(500),
    ADD COLUMN notes_2 VARCHAR(500),
    ADD COLUMN notes_3 VARCHAR(500),
    ADD COLUMN notes_4 VARCHAR(500),
    ADD COLUMN notes_5 VARCHAR(500);
